name: Deploy to Azure Containers

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: taskflow.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t taskflow.azurecr.io/taskflow:${{ github.sha }} .
        docker push taskflow.azurecr.io/taskflow:${{ github.sha }}

    - name: Deploy to Azure
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az container create \
            --resource-group pms \
            --name taskflow \
            --image taskflow.azurecr.io/taskflow:${{ github.sha }} \
            --registry-login-server taskflow.azurecr.io \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.ACR_PASSWORD }}
            --environment-variables \
            DB_Host=${{ secrets.DB_HOST }} \
            DB_User=${{ secrets.DB_USER }} \
            DB_Password=${{ secrets.DB_PASSWORD }} \
            DB_Name=${{ secrets.DB_NAME }} \
            JWT_Secret=${{ secrets.JWT_SECRET }} \
            PORT=3000 \
            NODE_ENV=production
            SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}
            SENDGRID_USER_EMAIL=${{ secrets.SENDGRID_USER_EMAIL }}
            BACKEND_URL=${{ secrets.BACKEND_URL }}
